# Werkcollege-opdrachten Week 1.2

## Voorbereiding

Importeer in het codeblok hieronder de packages die worden gebruikt om data in te lezen. Geef er ook de gebruikelijke aliassen aan.<br>
N.B.: de 2 reeds geschreven coderegels zorgen ervoor dat eventuele warnings, die code-outputs lelijker maken, uitgezet worden.

In [5]:

import warnings
warnings.simplefilter('ignore')

Zet de volgende bestanden in een makkelijk terug te vinden map:
- go_sales_train.sqlite
- go_crm_train.sqlite
- go_staff_train.sqlite

Bestudeer de bovenste 3 bestanden in DB Browser (SQLite), <a href="https://sqlitebrowser.org/dl/">hier</a> te downloaden. Wat valt je op qua datatypen?<br>

## Databasetabel inlezen

Creëer een databaseconnectie met het bestand go_sales_train.sqlite.

In [1]:
import sqlite3

try:
    sqliteConnection = sqlite3.connect('go_sales_train.sqlite')
    cursor = sqliteConnection.cursor()
    print('Db created and connected succesfull')
except sqlite3.Error as error:
    print('Error occured: ', error)

Db created and connected succesfull

<b>Let goed op:</b><br>
Als je per ongeluk een verkeerde bestandsnaam ingeeft, maakt Python zélf een leeg databasebestand aan! Er ontstaat dan dus een nieuwe .sqlite, en dat is nadrukkelijk <u>niet de bedoeling.</u>

Gebruik de onderstaande sql_query om te achterhalen welke databasetabellen in go_sales_train zitten.

In [2]:
sql_query = "SELECT name FROM sqlite_master WHERE type='table';"

cursor.execute(sql_query)

result = cursor.fetchall()

print(result)
#Vul dit codeblok verder in

[('country',), ('order_details',), ('order_header',), ('order_method',), ('product',), ('product_line',), ('product_type',), ('retailer_site',), ('return_reason',), ('returned_item',), ('sales_branch',), ('sales_staff',)]

Krijg je lege output? Dan heb je per ongeluk een leeg  databasebestand (.sqlite) aangemaakt.<br>
Lees de informatie onder het kopje <u>Let goed op:</u> hierboven nog eens goed door.

Gebruik de gecreëerde databaseconnectie om de resultaten van de volgende query in een DataFrame te zetten:<br>
*SELECT * FROM sales_staff*

In [18]:
sql_query_2 = "SELECT * FROM sales_staff;"
cursor.execute(sql_query_2)

sales_staff = cursor.fetchall()

print(sales_staff)

[(4, 'Denis', 'Pagé', 'Branch Manager', '+33 1 68 94 52 20', 325, '+33 1 68 94 56 60', 'DPage@grtd123.com', '1996-11-03', 6), (5, 'Élizabeth', 'Michel', 'Level 3 Sales Representative', '+33 1 68 94 52 20', 336, '+33 1 68 94 56 60', 'EMichel@grtd123.com', '1995-06-08', 6), (6, 'Émile', 'Clermont', 'Level 1 Sales Representative', '+33 1 68 94 52 20', 378, '+33 1 68 94 56 60', 'EClermont@grtd123.com', '1998-04-07', 6), (7, 'Étienne', 'Jauvin', 'Level 2 Sales Representative', '+33 1 68 94 52 20', 398, '+33 1 68 94 56 60', 'EJauvin@grtd123.com', '1997-08-16', 6), (12, 'Elsbeth', 'Wiesinger', 'Level 2 Sales Representative', '+(49) 40 663 1990', 1818, '+(49) 40 663 4571', 'EWiesinger@grtd123.com', '1997-02-27', 13), (13, 'Else', 'Mörike', 'Regional Manager', '+(49) 40 663 1990', 1865, '+(49) 40 663 4571', 'EMorike@grtd123.com', '1999-06-02', 13), (14, 'Frank', 'Fuchs', 'Branch Manager', '+(49) 40 663 1990', 1847, '+(49) 40 663 4571', 'FFuchs@grtd123.com', '1997-01-12', 13), (15, 'Gunter', 'Erler', 'Level 2 Sales Representative', '+(49) 40 663 1990', 1823, '+(49) 40 663 4571', 'GErler@grtd123.com', '1998-03-05', 13), (16, 'Björn', 'Winkler', 'Level 3 Sales Representative', '+(49) 89 882 3456', 224, '+(49) 89 882 3455', 'BWinkler@grtd123.com', '1996-07-03', 14), (17, 'Fritz', 'Hirsch', 'Branch Manager', '+(49) 89 882 3456', 225, '+(49) 89 882 3455', 'FHirsch@grtd123.com', '1996-09-12', 14), (18, 'Jörg', 'Kunze', 'District Manager', '+(49) 89 882 3456', 234, '+(49) 89 882 3455', 'JKunze@grtd123.com', '2000-01-07', 14), (19, 'Silvano', 'Allessori', 'Level 2 Sales Representative', '+33 1 68 94 52 20', 317, '+33 1 68 94 56 60', 'SAllessori@grtd123.com', '1998-12-06', 7), (20, 'Maria', 'Iacobucci', 'Branch Manager', '+(39) 02 41 05 400', None, '+(39) 02 41 20 549', 'MIacobucci@grtd123.com', '1996-08-18', 7), (21, 'Alessandra', 'Torta', 'Level 3 Sales Representative', '+(39) 02 79 53 780', None, '+(39) 02 79 53 477', 'ATorta@grtd123.com', '1997-02-13', 7), (22, 'Belinda', 'Jansen-Velasquez', 'Level 1 Sales Representative', '+31 (0)20 692 93 94', 187, '+31 (0)20 692 93 06', 'BVelasquez@grtd123.com', '1999-02-12', 9), (23, 'Ellen', 'Shapiro', 'Level 2 Sales Representative', '+31 (0)20 692 93 94', 179, '+31 (0)20 692 93 06', 'EShapiro@grtd123.com', '1999-01-15', 9), (24, 'Jan', 'Haverkamp', 'Level 2 Sales Representative', '+31 (0)20 692 93 94', 163, '+31 (0)20 692 93 06', 'JHaverkamp@grtd123.com', '1998-07-18', 9), (25, 'Kick', 'Kalkman', 'Branch Manager', '+31 (0)20 692 93 94', 197, '+31 (0)20 692 93 06', 'KKalkman@grtd123.com', '1995-09-06', 9), (26, 'Maria', 'Laponder', 'Level 3 Sales Representative', '+31 (0)20 692 93 94', 144, '+31 (0)20 692 93 06', 'MLaponder@grtd123.com', '1995-10-10', 9), (27, 'Anders', 'Nilsson', 'Level 2 Sales Representative', '+(46) 08 753 116', 236, '+(46) 08 752 592', 'ANilsson@grtd123.com', '1998-08-14', 15), (28, 'Bengt', 'Gradin', 'Level 1 Sales Representative', '+(46) 08 753 116', 284, '+(46) 08 752 592', 'BGradin@grtd123.com', '1999-01-13', 15), (29, 'Irene', 'Engelbrektsson', 'Level 2 Sales Representative', '+(46) 08 753 116', 213, '+(46) 08 752 592', 'IEngelbrektsson@grtd123.com', '1998-02-18', 15), (30, 'Karin', 'Bergström', 'Branch Manager', '+(46) 08 753 116', 215, '+(46) 08 752 592', 'KBergstrom@grtd123.com', '1998-04-27', 15), (43, 'Martine', 'Vachon', 'Level 2 Sales Representative', '1 (403) 232-5986', 312, '1 (403) 232-5831', 'MVachon@grtd123.com', '1998-03-18', 17), (44, 'Harold', 'Townsend', 'Level 3 Sales Representative', '1 (403) 232-5986', 315, '1 (403) 232-5831', 'HTownsend@grtd123.com', '1992-08-08', 17), (45, 'Sally', 'White', 'Branch Manager', '1 (403) 232-5986', 317, '1 (403) 232-5831', 'SWhite@grtd123.com', '1992-03-26', 17), (46, 'Sherry', 'Rowland', 'Level 2 Sales Representative', '1 (403) 232-5986', 325, '1 (403) 232-5831', 'SRowland@grtd123.com', '1997-02-13', 17), (47, 'Frank', 'Bretton', 'District Manager', '1 (403) 232-5986', 301, '1 (403) 232-5831', 'FBretton@grtd123.com', '2000-03-01', 17), (48, 'Georges', 'Saint-Germain', 'Branch Manager', '1 (416) 493-5595', 1245, '1 (416) 496-9667', 'GSaintgermain@grtd123.com', '1991-10-27', 18), (49, 'Carole', 'Claudel', 'Level 2 Sales Representative', '1 (416) 493-5595', 2378, '1 (416) 496-9667', 'CClaudel@grtd123.com', '1994-08-12', 18), (50, 'Donald', 'Chow', 'Level 3 Sales Representative', '1 (416) 493-5595', 6587, '1 (416) 490-7420', 'DChow@grtd123.com', '1990-04-14', 18), (51, 'Samantha', 'Pierce', 'Level 2 Sales Representative', '1 (416) 493-5595', 4589, '1 (416) 490-7420', 'SPierce@grtd123.com', '1998-03-15', 18), (52, 'Brendon', 'Pike', 'Level 1 Sales Representative', '1 (416) 493-5595', 2189, '1 (416) 496-9667', 'BPike@grtd123.com', '1999-12-20', 18), (53, 'Alex', 'Rodriguez', 'Branch Manager', '1 (617) 268-6754', 1334, '1 (617) 268-3464', 'ARodriguez@grtd123.com', '1992-02-07', 19), (54, 'Allisia', 'Wilcox', 'Level 2 Sales Representative', '1 (617) 268-6754', 1436, '1 (617) 268-3464', 'AWilcox@grtd123.com', '1997-07-12', 19), (55, 'Pierre', 'Lavoie', 'Level 3 Sales Representative', '1 (617) 268-6754', 1447, '1 (617) 268-3464', 'PLavoie@grtd123.com', '1994-10-08', 19), (56, 'Rhonda', 'Cummings', 'Level 2 Sales Representative', '1 (617) 268-6754', 1384, '1 (617) 268-3464', 'RCummings@grtd123.com', '1996-05-06', 19), (57, 'Samantha', 'Floyd', 'Branch Manager', '1 (206) 292-0012', 331, '1 (206) 292-3312', 'SFloyd@grtd123.com', '1995-07-17', 20), (58, 'Ashley', 'McCormick', 'Level 2 Sales Representative', '1 (206) 292-0012', 384, '1 (206) 292-3312', 'AMccormick@grtd123.com', '1996-04-15', 20), (59, 'Audrey', 'Lastman', 'Level 3 Sales Representative', '1 (206) 292-0012', 396, '1 (206) 292-3312', 'ALastman@grtd123.com', '1995-02-15', 20), (60, 'Bart', 'Scott', 'Level 2 Sales Representative', '1 (206) 292-0012', 312, '1 (206) 292-3312', 'BScott@grtd123.com', '1997-11-28', 20), (61, 'Julie', 'Olsen', 'Branch Manager', '1 (310) 281-5722', 2045, '1 (310) 281-9087', 'JOlsen@grtd123.com', '1998-02-18', 22), (62, 'Ken', 'Chambers', 'Level 2 Sales Representative', '1 (310) 281-5722', 2123, '1 (310) 281-9087', 'KChambers@grtd123.com', '1998-04-03', 22), (63, 'Chad', 'Michaels', 'Level 3 Sales Representative', '1 (310) 281-5722', 2178, '1 (310) 281-9087', 'CMichaels@grtd123.com', '1996-05-17', 22), (64, 'Maureen', 'Hoffman', 'Level 2 Sales Representative', '1 (310) 281-5722', 2160, '1 (310) 281-9087', 'MHoffman@grtd123.com', '1998-07-22', 22), (65, 'Corey', 'Wright', 'Branch Manager', '1 (305) 557-4810', 3490, '1 (305) 557-7650', 'CWright@grtd123.com', '1995-10-11', 21), (66, 'Dale', 'Fowler', 'Level 2 Sales Representative', '1 (305) 557-4810', 3652, '1 (305) 557-7650', 'DFowler@grtd123.com', '1998-02-12', 21), (67, 'Lowell', 'Johnson', 'Level 2 Sales Representative', '1 (305) 557-4810', 3335, '1 (305) 557-7650', 'LJohnson@grtd123.com', '1997-03-06', 21), (68, 'Margaret', 'Lewiston', 'Level 2 Sales Representative', '1 (305) 557-4810', 3121, '1 (305) 557-7650', 'MLewiston@grtd123.com', '1996-08-18', 21), (69, 'Eric', 'Carson', 'Level 2 Sales Representative', '1 (617) 268-6754', 1387, '1 (617) 268-3464', 'ECarson@grtd123.com', '1996-11-08', 19), (70, 'Valerie', 'Cohen', 'Level 2 Sales Representative', '1 (305) 557-4810', 3547, '1 (305) 557-7650', 'VCohen@grtd123.com', '1997-07-23', 21), (71, 'Estelle', 'Johnson', 'District Manager', '1 (617) 268-6754', 1399, '1 (617) 268-3464', 'EJohnson@grtd123.com', '1998-12-04', 19), (72, 'Greg', 'Belding', 'Regional Manager', '1 (206) 292-0012', 373, '1 (206) 292-3312', 'GBelding@grtd123.com', '1998-12-04', 20), (73, 'Harold', 'Germaine', 'Level 1 Sales Representative', '1 (310) 281-5722', 2088, '1 (310) 281-9087', 'HGermaine@grtd123.com', '1998-11-19', 22), (74, 'Janice', 'Thomas', 'Level 1 Sales Representative', '1 (305) 557-4810', 3207, '1 (305) 557-7650', 'JThomas@grtd123.com', '1998-06-12', 21), (75, 'Julie', 'Béchard', 'Branch Manager', '+33 4 52 26 33 88', 1315, '+33 4 66 35 98 95', 'JBechard@grtd123.com', '1994-09-03', 23), (76, 'Florence', 'Martin', 'Level 2 Sales Representative', '+33 4 52 26 33 88', 1318, '+33 4 66 35 98 95', 'FMartin@grtd123.com', '1997-08-23', 23), (77, 'Daniel', 'Turpin', 'Level 2 Sales Representative', '+33 4 52 26 33 88', 1316, '+33 4 66 35 98 95', 'DTurpin@grtd123.com', '1998-05-13', 23), (78, 'Frédéric', 'Samson', 'Level 3 Sales Representative', '+33 4 52 26 33 88', 1322, '+33 4 66 35 98 95', 'FSamson@grtd123.com', '1994-02-21', 23), (79, 'Lucía', 'Reyna', 'Branch Manager', '+(525) 549 6090', 452, '+(52) 549 6088', 'LReyna@grtd123.com', '1997-03-10', 24), (80, 'Ana', 'Orozco', 'Level 2 Sales Representative', '+(525) 549 6090', 449, '+(52) 549 6088', 'AOrozco@grtd123.com', '1997-10-11', 24), (81, 'Gabriela', 'Rojas', 'Level 2 Sales Representative', '+(525) 549 6090', 465, '+(52) 549 6088', 'GRojas@grtd123.com', '1998-03-19', 24), (83, 'Machiko', 'Iseya', 'Level 1 Sales Representative', '81-3-6259-6601', 2236, '81-3-6208-4445', 'MIseya@grtd123.com', '1999-02-21', 25), (85, 'Genzo', 'Imori', 'Level 3 Sales Representative', '81-3-6259-6601', 2245, '81-3-6208-4445', 'GImori@grtd123.com', '1998-01-05', 25), (87, 'Kazumi', 'Uragome', 'District Manager', '81-6-616-5656', 2156, '81-6-616-5657', 'KUragome@grtd123.com', '1998-11-05', 26), (88, 'Masuzo', 'Kakui', 'Level 3 Sales Representative', '81-6-616-5656', 2155, '81-6-616-5657', 'MKakui@grtd123.com', '1998-05-12', 26), (89, 'Alice', 'Walter', 'Branch Manager', '+(61) 03 2982  4242', 1845, '+(61) 03 2982  4243', 'AWalter@grtd123.com', '1999-09-08', 28), (90, 'Dave', 'Smythe', 'Level 1 Sales Representative', '+(61) 03 2982  4242', 1875, '+(61) 03 2982  4243', 'DSmythe@grtd123.com', '2000-01-10', 28), (91, 'Donald', 'Ward', 'Level 2 Sales Representative', '+(61) 03 2982  4242', 1874, '+(61) 03 2982  4243', 'DWard@grtd123.com', '1999-11-29', 28), (92, 'Jake', 'Cartel', 'Level 2 Sales Representative', '+(61) 03 2982  4242', 1648, '+(61) 03 2982  4243', 'JCartel@grtd123.com', '1999-12-15', 28), (93, 'John', 'Sinden', 'Level 3 Sales Representative', '+(61) 03 2982  4242', 1892, '+(61) 03 2982  4243', 'JSinden@grtd123.com', '1999-11-30', 28), (94, 'Yolanda', 'Torres', 'Level 3 Sales Representative', '+35 94 322 3540', 125, '+35 91 548 1637', 'YTorres@grtd123.com', '1995-08-29', 29), (95, 'Tomás', 'Iglesias', 'Level 2 Sales Representative', '+35 94 322 3540', 325, '+35 91 548 1637', 'TIglesias@grtd123.com', '1998-02-19', 29), (96, 'Bayard', 'Lopes', 'Branch Manager', '+55 (11) 344-4444', 3490, '+55 (11) 333-2223', 'BLopes@grtd123.com', '1997-08-12', 30), (97, 'Viviam', 'Barros', 'Level 3 Sales Representative', '+55 (11) 344-4444', 3364, '+55 (11) 333-2223', 'VBarros@grtd123.com', '2001-02-10', 30), (98, 'Eduardo', 'Guimarães', 'Level 2 Sales Representative', '+55 (11) 344-4444', 1442, '+55 (11) 333-2223', 'EGuimaraes@grtd123.com', '1999-02-14', 30), (99, 'Helena', 'Lindholm', 'Level 3 Sales Representative', '+358(0)17 - 433 127', 489, '+358(0)17 - 433 129', 'HLindholm@grtd123.com', '1997-08-17', 31), (100, 'Tuomas', 'Savolainen', 'Level 2 Sales Representative', '+358(0)17 - 433 127', 825, '+358(0)17 - 433 129', 'TSavolainen@grtd123.com', '1998-07-23', 31), (101, 'Chang-ho', 'Kim', 'Level 2 Sales Representative', '82-2-778-6587', 1228, '82-2-778-6586', 'CKim@grtd123.com', '1998-12-15', 32), (102, 'Jung-ho', 'Choi', 'Level 3 Sales Representative', '82-2-778-6587', 2641, '82-2-778-6586', 'JChoi@grtd123.com', '1998-11-27', 32), (103, 'Kwei-Ping', 'Kao', 'Level 2 Sales Representative', '886-2-2975-1988', 1541, '886-2-2989-4978', 'KKwao@grtd123.com', '1998-10-07', 33), (104, 'Chin-Tsai', 'Fang', 'Level 3 Sales Representative', '886-2-2975-1988', 2311, '886-2-2989-4978', 'CFon@grtd123.com', '1996-05-08', 33), (105, 'Xiangyong', 'Wang', 'Level 2 Sales Representative', '86-21-6790-5612', 334, '86-21-6790-5612', 'XWang@grtd123.com', '1998-05-07', 34), (106, 'Fei', 'Meng', 'Level 3 Sales Representative', '86-21-6790-5612', 365, '86-21-6790-5612', 'FMeng@grtd123.com', '1998-03-25', 34), (107, 'Walter', 'Taylor', 'Branch Manager', '+(44) 181 2033144', 3547, '+(44) 181 5030282', 'WTaylor@grtd123.com', '1995-06-09', 35), (108, 'Penelope', 'Tamrine', 'General Manager', '+(44) 181 2033144', 3542, '+(44) 181 5030282', 'PTamrine@grtd123.com', '1998-12-18', 35), (109, 'Humphrey', 'Willoughby', 'Level 2 Sales Representative', '+(44) 181 2033144', 3544, '+(44) 181 5030282', 'HWilloughby@grtd123.com', '1998-06-12', 35), (110, 'James', 'Ross-Hythe', 'Level 3 Sales Representative', '+(44) 181 2033144', 3621, '+(44) 181 5030282', 'JHythe@grtd123.com', '1997-09-12', 35), (111, 'Polly', 'Linton', 'Branch Manager', '+(44) 121 3505267', 1216, '+(44) 121 3583843', 'PLinton@grtd123.com', '1996-06-18', 36), (112, 'Josef', 'Lopez', 'Level 1 Sales Representative', '+(44) 121 3505267', 1287, '+(44) 121 3583843', 'JLopez@grtd123.com', '1999-01-02', 36), (113, 'Keith', 'Reed', 'Level 1 Sales Representative', '+(44) 121 3505267', 1198, '+(44) 121 3583843', 'KReed@grtd123.com', '1999-06-15', 36), (114, 'Janet', 'Walker', 'Level 3 Sales Representative', '+(44) 121 3505267', 1233, '+(44) 121 3583843', 'JWalker@grtd123.com', '1995-07-27', 36), (115, 'Emily', 'Browne', 'Level 2 Sales Representative', '+(44) 121 3505267', 1247, '+(44) 121 3583843', 'EBrowne@grtd123.com', '1998-07-20', 36), (116, 'Susanne', 'Sommer', 'Level 2 Sales Representative', '+(41) 17 12 13 14', 1115, '+(41) 17 12 13 20', 'SSommer@grtd123.com', '2000-01-17', 37), (117, 'Frank', 'Jever', 'Level 3 Sales Representative', '+(41) 17 12 13 14', 1154, '+(41) 17 12 13 20', 'FJever@grtd123.com', '1999-10-18', 37), (118, 'Gianni', 'Vertemati', 'Level 1 Sales Representative', '+(41) 17 12 13 14', 1254, '+(41) 17 12 13 20', 'GVertemati@grtd123.com', '2000-02-10', 37), (119, 'Gracy', 'Gellens', 'Branch Manager', '+32 16 20.73.21', 1349, '+32 16 20.73.32', 'GGellens@grtd123.com', '1999-09-10', 38), (120, 'Giele', 'Laermans', 'Level 1 Sales Representative', '+32 16 20.73.21', 1340, '+32 16 20.73.32', 'GLaermans@grtd123.com', '1999-11-15', 38), (121, 'François', 'De Crée', 'Level 1 Sales Representative', '+32 16 20.73.21', 1642, '+32 16 20.73.32', 'FDecree@grtd123.com', '1999-12-01', 38), (122, 'Yvette', 'Lattrez', 'Level 3 Sales Representative', '+32 16 20.73.21', 1633, '+32 16 20.73.32', 'YLattrez@grtd123.com', '1999-12-09', 38), (123, 'Willi', 'Seefelder', 'Level 2 Sales Representative', '+(43) 13 79 56 32', 325, '+(43) 13 79 56 33', 'WSeefelder@grtd123.com', '1998-10-28', 39), (124, 'Sabine', 'Grüner', 'Level 3 Sales Representative', '+(43) 13 79 56 32', 348, '+(43) 13 79 56 33', 'SGruner@grtd123.com', '1998-02-18', 39)]

## Datumkolommen

Zoals je misschien al hebt gezien in DB Browser, zijn datums als TEXT opgeslagen, en niet als DATE, DATETIME o.i.d. Hier moeten we dus nog even "typische datumkolommen" van maken. Dat doen we met de volgende code:

In [ ]:
import pandas as pd


column_names = [desc[0] for desc in cursor.description]

sales_staff = pd.DataFrame(sales_staff, columns=column_names)

sales_staff['DATE_HIRED'] = pd.to_datetime(sales_staff['DATE_HIRED'])
sales_staff.dtypes

SALES_STAFF_CODE              int64
FIRST_NAME                   object
LAST_NAME                    object
POSITION_EN                  object
WORK_PHONE                   object
EXTENSION                   float64
FAX                          object
EMAIL                        object
DATE_HIRED           datetime64[ns]
SALES_BRANCH_CODE             int64
dtype: object

Als we hier het jaar uit willen halen, schrijven we:

In [25]:
pd.DatetimeIndex(sales_staff['DATE_HIRED']).quarter
# pd.DatetimeIndex(sales_staff['DATE_HIRED']).day
# pd.DatetimeIndex(sales_staff['DATE_HIRED']).year

Index([4, 2, 2, 3, 1, 2, 1, 1, 3, 3,
       ...
       3, 1, 4, 1, 3, 4, 4, 4, 4, 1],
      dtype='int32', name='DATE_HIRED', length=102)

Deze zelfde syntax is te gebruiken voor het extraheren van kwartalen, maanden, weken en dagen. Probeer het maar eens!

## DataFrames uitsplitsen en opbouwen met Series

De volgende 5 kolommen hebben betrekking op de contactdetails van elke medewerker in dit DataFrame:
- SALES_STAFF_CODE
- WORK_PHONE
- EXTENSION
- FAX
- EMAIL

Maak van elk van deze 5 kolommen een serie.

In [45]:
s1 = sales_staff.loc[:, 'SALES_STAFF_CODE']
s2 = sales_staff.loc[:, 'WORK_PHONE']
s3 = sales_staff.loc[:, 'EXTENSION']
s4 = sales_staff.loc[:, 'FAX']
s5 = sales_staff.loc[:, 'EMAIL']

s1

0        4
1        5
2        6
3        7
4       12
      ...
97     120
98     121
99     122
100    123
101    124
Name: SALES_STAFF_CODE, Length: 102, dtype: int64

Zet allevijf gecreëerde series als kolommen naast elkaar in een DataFrame (*contact_details*). Gebruik pd.concat(...)<br>
Hulpvraag: welke waarde geef je aan de axis-parameter?

In [47]:
contact_details =  pd.concat([s1, s2, s3, s4, s5], axis=1)
contact_details

,SALES_STAFF_CODE,WORK_PHONE,EXTENSION,FAX,EMAIL
0,4,+33 1 68 94 52 20,325.0,+33 1 68 94 56 60,DPage@grtd123.com
1,5,+33 1 68 94 52 20,336.0,+33 1 68 94 56 60,EMichel@grtd123.com
2,6,+33 1 68 94 52 20,378.0,+33 1 68 94 56 60,EClermont@grtd123.com
3,7,+33 1 68 94 52 20,398.0,+33 1 68 94 56 60,EJauvin@grtd123.com
4,12,+(49) 40 663 1990,1818.0,+(49) 40 663 4571,EWiesinger@grtd123.com
...,...,...,...,...,...
97,120,+32 16 20.73.21,1340.0,+32 16 20.73.32,GLaermans@grtd123.com
98,121,+32 16 20.73.21,1642.0,+32 16 20.73.32,FDecree@grtd123.com
99,122,+32 16 20.73.21,1633.0,+32 16 20.73.32,YLattrez@grtd123.com
100,123,+(43) 13 79 56 32,325.0,+(43) 13 79 56 33,WSeefelder@grtd123.com
101,124,+(43) 13 79 56 32,348.0,+(43) 13 79 56 33,SGruner@grtd123.com

## Series en DataFrames maken vanuit lists en dictionaries

Met .head(*getal*) kan je de bovenste *getal* rijen van een tabel selecteren.<br>
Selecteer op deze manier de bovenste 5 rijen van *contact_details*.<br>
Sla dit resultaat op in een nieuw DataFrame.

In [50]:
newDF = pd.concat([contact_details.head(5)], axis=1)
newDF

,SALES_STAFF_CODE,WORK_PHONE,EXTENSION,FAX,EMAIL
0,4,+33 1 68 94 52 20,325.0,+33 1 68 94 56 60,DPage@grtd123.com
1,5,+33 1 68 94 52 20,336.0,+33 1 68 94 56 60,EMichel@grtd123.com
2,6,+33 1 68 94 52 20,378.0,+33 1 68 94 56 60,EClermont@grtd123.com
3,7,+33 1 68 94 52 20,398.0,+33 1 68 94 56 60,EJauvin@grtd123.com
4,12,+(49) 40 663 1990,1818.0,+(49) 40 663 4571,EWiesinger@grtd123.com

Aan deze 10 rijen met contactdetails willen we 3 kolommen toevoegen: 'FIRST_LANGUAGE', 'SECOND_LANGUAGE' & 'THIRD_LANGUAGE'.<br>
Iedereens 'First Language' is Engels, afgekort 'EN'. Maak een lijst waarin 5x 'EN' staat.<br>
Converteer deze lijst vervolgens naar een serie en voeg deze horizontaal samen met het resultaat van de vorige opdracht.<br>
Vergeet niet een passende naam te geven aan de nieuw ontstane kolom.

In [54]:
list = ['EN', 'EN', 'EN', 'EN', 'EN']
list = pd.Series(list, name='FIRST_LANGUAGE')

newDF2 = pd.concat([contact_details, list], axis=1)

newDF2

,SALES_STAFF_CODE,WORK_PHONE,EXTENSION,FAX,EMAIL,FIRST_LANGUAGE
0,4,+33 1 68 94 52 20,325.0,+33 1 68 94 56 60,DPage@grtd123.com,EN
1,5,+33 1 68 94 52 20,336.0,+33 1 68 94 56 60,EMichel@grtd123.com,EN
2,6,+33 1 68 94 52 20,378.0,+33 1 68 94 56 60,EClermont@grtd123.com,EN
3,7,+33 1 68 94 52 20,398.0,+33 1 68 94 56 60,EJauvin@grtd123.com,EN
4,12,+(49) 40 663 1990,1818.0,+(49) 40 663 4571,EWiesinger@grtd123.com,EN
...,...,...,...,...,...,...
97,120,+32 16 20.73.21,1340.0,+32 16 20.73.32,GLaermans@grtd123.com,NaN
98,121,+32 16 20.73.21,1642.0,+32 16 20.73.32,FDecree@grtd123.com,NaN
99,122,+32 16 20.73.21,1633.0,+32 16 20.73.32,YLattrez@grtd123.com,NaN
100,123,+(43) 13 79 56 32,325.0,+(43) 13 79 56 33,WSeefelder@grtd123.com,NaN
101,124,+(43) 13 79 56 32,348.0,+(43) 13 79 56 33,SGruner@grtd123.com,NaN

Maak nu de tweede kolom ('SECOND_LANGUAGE'). Maak daarvoor een dictionary, met daarin...
- Als keys: alle indexen uit het resultaat van het vorige codeblok.
- Als values: bij de eerste 3 elementen 'FR' (Frankrijk), bij de laatste 2 'DE' (Duitsland).

Maak vervolgens ook hier weer een serie van en voeg ook deze weer horizontaal samen met het rsultaat van de vorige opdracht.<br>
Vergeet niet een passende naam te geven aan de nieuw ontstane kolom.

In [64]:
dictionary = {0 : 'FR', 1 : 'FR', 2 : 'FR', 3 :  'DE', 4 : 'DE'}
dictionary = pd.Series(dictionary, name="SECOND_LANGUAGE")

newDF3 = pd.concat([newDF2, dictionary], axis=1)

newDF3

,SALES_STAFF_CODE,WORK_PHONE,EXTENSION,FAX,EMAIL,FIRST_LANGUAGE,SECOND_LANGUAGE
0,4,+33 1 68 94 52 20,325.0,+33 1 68 94 56 60,DPage@grtd123.com,EN,FR
1,5,+33 1 68 94 52 20,336.0,+33 1 68 94 56 60,EMichel@grtd123.com,EN,FR
2,6,+33 1 68 94 52 20,378.0,+33 1 68 94 56 60,EClermont@grtd123.com,EN,FR
3,7,+33 1 68 94 52 20,398.0,+33 1 68 94 56 60,EJauvin@grtd123.com,EN,DE
4,12,+(49) 40 663 1990,1818.0,+(49) 40 663 4571,EWiesinger@grtd123.com,EN,DE
...,...,...,...,...,...,...,...
97,120,+32 16 20.73.21,1340.0,+32 16 20.73.32,GLaermans@grtd123.com,NaN,NaN
98,121,+32 16 20.73.21,1642.0,+32 16 20.73.32,FDecree@grtd123.com,NaN,NaN
99,122,+32 16 20.73.21,1633.0,+32 16 20.73.32,YLattrez@grtd123.com,NaN,NaN
100,123,+(43) 13 79 56 32,325.0,+(43) 13 79 56 33,WSeefelder@grtd123.com,NaN,NaN
101,124,+(43) 13 79 56 32,348.0,+(43) 13 79 56 33,SGruner@grtd123.com,NaN,NaN

Maak ten slotte de derde kolom ('THIRD_LANGUAGE') door een dictionary te maken met daarin...
- Als key: de naam van de nieuwe kolom. Zie je het verschil qua keys met de vorige opdracht?
- Als waarde: een lijst met daarin 'NL', 'NL', 'JPN', 'JPN', 'KOR'.

Converteer deze dictionary nu naar een DataFrame en voeg deze horizontaal samen met het resultaat van de vorige opdracht.<br>
Waarom hoef je hierna de nieuw ontstane kolom geen passende naam meer te geven?

In [68]:
lijst3 = ["NL", "NL", "JPN", "JPN", "KOR"]
dictionary2 = {
    'THIRD_LANGUAGE' : lijst3
}

dictionary2 = pd.DataFrame(dictionary2)

newDF4 = pd.concat([newDF3, dictionary2], axis=1)

newDF4

,SALES_STAFF_CODE,WORK_PHONE,EXTENSION,FAX,EMAIL,FIRST_LANGUAGE,SECOND_LANGUAGE,THIRD_LANGUAGE
0,4,+33 1 68 94 52 20,325.0,+33 1 68 94 56 60,DPage@grtd123.com,EN,FR,NL
1,5,+33 1 68 94 52 20,336.0,+33 1 68 94 56 60,EMichel@grtd123.com,EN,FR,NL
2,6,+33 1 68 94 52 20,378.0,+33 1 68 94 56 60,EClermont@grtd123.com,EN,FR,JPN
3,7,+33 1 68 94 52 20,398.0,+33 1 68 94 56 60,EJauvin@grtd123.com,EN,DE,JPN
4,12,+(49) 40 663 1990,1818.0,+(49) 40 663 4571,EWiesinger@grtd123.com,EN,DE,KOR
...,...,...,...,...,...,...,...,...
97,120,+32 16 20.73.21,1340.0,+32 16 20.73.32,GLaermans@grtd123.com,NaN,NaN,NaN
98,121,+32 16 20.73.21,1642.0,+32 16 20.73.32,FDecree@grtd123.com,NaN,NaN,NaN
99,122,+32 16 20.73.21,1633.0,+32 16 20.73.32,YLattrez@grtd123.com,NaN,NaN,NaN
100,123,+(43) 13 79 56 32,325.0,+(43) 13 79 56 33,WSeefelder@grtd123.com,NaN,NaN,NaN
101,124,+(43) 13 79 56 32,348.0,+(43) 13 79 56 33,SGruner@grtd123.com,NaN,NaN,NaN

## Data toevoegen

### Rijen

Gebruik de originele databasetabel *sales_staff*.<br>
Voeg een extra rij toe met eigen invulling. Zorg ervoor dat de index netjes doorloopt.<br>
Hulpvraag: welke waarde geef je nu aan axis?

In [84]:
object1 = {'SALES_STAFF_CODE' : '1301',
           'FIRST_NAME' : 'Bob',
            'LAST_NAME' :  'de Bouwer',
             'POSITION_EN' : 'Verkoper',
              'WORK_PHONE' :  '+31 1 45 67 89 01'}
object1 = pd.DataFrame([object1])
newDF5 = pd.concat([sales_staff, object1], axis=0, ignore_index=True)

newDF5

,SALES_STAFF_CODE,FIRST_NAME,LAST_NAME,POSITION_EN,WORK_PHONE,EXTENSION,FAX,EMAIL,DATE_HIRED,SALES_BRANCH_CODE
0,4,Denis,Pagé,Branch Manager,+33 1 68 94 52 20,325.0,+33 1 68 94 56 60,DPage@grtd123.com,1996-11-03,6.0
1,5,Élizabeth,Michel,Level 3 Sales Representative,+33 1 68 94 52 20,336.0,+33 1 68 94 56 60,EMichel@grtd123.com,1995-06-08,6.0
2,6,Émile,Clermont,Level 1 Sales Representative,+33 1 68 94 52 20,378.0,+33 1 68 94 56 60,EClermont@grtd123.com,1998-04-07,6.0
3,7,Étienne,Jauvin,Level 2 Sales Representative,+33 1 68 94 52 20,398.0,+33 1 68 94 56 60,EJauvin@grtd123.com,1997-08-16,6.0
4,12,Elsbeth,Wiesinger,Level 2 Sales Representative,+(49) 40 663 1990,1818.0,+(49) 40 663 4571,EWiesinger@grtd123.com,1997-02-27,13.0
...,...,...,...,...,...,...,...,...,...,...
98,121,François,De Crée,Level 1 Sales Representative,+32 16 20.73.21,1642.0,+32 16 20.73.32,FDecree@grtd123.com,1999-12-01,38.0
99,122,Yvette,Lattrez,Level 3 Sales Representative,+32 16 20.73.21,1633.0,+32 16 20.73.32,YLattrez@grtd123.com,1999-12-09,38.0
100,123,Willi,Seefelder,Level 2 Sales Representative,+(43) 13 79 56 32,325.0,+(43) 13 79 56 33,WSeefelder@grtd123.com,1998-10-28,39.0
101,124,Sabine,Grüner,Level 3 Sales Representative,+(43) 13 79 56 32,348.0,+(43) 13 79 56 33,SGruner@grtd123.com,1998-02-18,39.0
102,1301,Bob,de Bouwer,Verkoper,+31 1 45 67 89 01,NaN,NaN,NaN,NaT,NaN

### Kolommen

Voeg een kolom *FULL_NAME* toe die de waarden van *FIRST_NAME* en *LAST_NAME* achter elkaar zet, gescheiden door een spatie.

In [86]:
newDF5['FULL_NAME'] = newDF5['FIRST_NAME'] + " " + newDF5['LAST_NAME']

newDF5

,SALES_STAFF_CODE,FIRST_NAME,LAST_NAME,POSITION_EN,WORK_PHONE,EXTENSION,FAX,EMAIL,DATE_HIRED,SALES_BRANCH_CODE,FULL_NAME
0,4,Denis,Pagé,Branch Manager,+33 1 68 94 52 20,325.0,+33 1 68 94 56 60,DPage@grtd123.com,1996-11-03,6.0,Denis Pagé
1,5,Élizabeth,Michel,Level 3 Sales Representative,+33 1 68 94 52 20,336.0,+33 1 68 94 56 60,EMichel@grtd123.com,1995-06-08,6.0,Élizabeth Michel
2,6,Émile,Clermont,Level 1 Sales Representative,+33 1 68 94 52 20,378.0,+33 1 68 94 56 60,EClermont@grtd123.com,1998-04-07,6.0,Émile Clermont
3,7,Étienne,Jauvin,Level 2 Sales Representative,+33 1 68 94 52 20,398.0,+33 1 68 94 56 60,EJauvin@grtd123.com,1997-08-16,6.0,Étienne Jauvin
4,12,Elsbeth,Wiesinger,Level 2 Sales Representative,+(49) 40 663 1990,1818.0,+(49) 40 663 4571,EWiesinger@grtd123.com,1997-02-27,13.0,Elsbeth Wiesinger
...,...,...,...,...,...,...,...,...,...,...,...
98,121,François,De Crée,Level 1 Sales Representative,+32 16 20.73.21,1642.0,+32 16 20.73.32,FDecree@grtd123.com,1999-12-01,38.0,François De Crée
99,122,Yvette,Lattrez,Level 3 Sales Representative,+32 16 20.73.21,1633.0,+32 16 20.73.32,YLattrez@grtd123.com,1999-12-09,38.0,Yvette Lattrez
100,123,Willi,Seefelder,Level 2 Sales Representative,+(43) 13 79 56 32,325.0,+(43) 13 79 56 33,WSeefelder@grtd123.com,1998-10-28,39.0,Willi Seefelder
101,124,Sabine,Grüner,Level 3 Sales Representative,+(43) 13 79 56 32,348.0,+(43) 13 79 56 33,SGruner@grtd123.com,1998-02-18,39.0,Sabine Grüner
102,1301,Bob,de Bouwer,Verkoper,+31 1 45 67 89 01,NaN,NaN,NaN,NaT,NaN,Bob de Bouwer

## Data wijzigen

### Datatypen

Door het attribuut .dtypes van een DataFrame op te vragen krijg je een serie die per kolom het datatype weergeeft. Doe dit bij de originele databasetabel *sales_staff*

In [87]:
sales_staff.dtypes

SALES_STAFF_CODE              int64
FIRST_NAME                   object
LAST_NAME                    object
POSITION_EN                  object
WORK_PHONE                   object
EXTENSION                   float64
FAX                          object
EMAIL                        object
DATE_HIRED           datetime64[ns]
SALES_BRANCH_CODE             int64
dtype: object

Hier valt op dat elke kolom het datatype 'object' heeft: Python leest dus alles als string. Wiskundige operaties zijn hierdoor niet mogelijk.<br>
We kunnen proberen om kolommen met getallen, bijvoorbeeld de 'extension', te converteren naar een int. Zie onderstaande code.

In [3]:
sales_staff['EXTENSION'] = sales_staff['EXTENSION'].astype(int)
sales_staff.dtypes

NameError: name 'sales_staff' is not defined

Dit lukt echter niet, omdat er in de kolom 'EXTENSION' lege waarden zitten die niet geconverteerd kunnen worden naar een int.<br>
Wél kan je deze naar een float converteren, zie onderstaande code:

In [88]:
sales_staff['EXTENSION'] = sales_staff['EXTENSION'].astype(float)
sales_staff.dtypes

SALES_STAFF_CODE              int64
FIRST_NAME                   object
LAST_NAME                    object
POSITION_EN                  object
WORK_PHONE                   object
EXTENSION                   float64
FAX                          object
EMAIL                        object
DATE_HIRED           datetime64[ns]
SALES_BRANCH_CODE             int64
dtype: object

Als we in de rij van 'EXTENSION' kijken zien we dat de conversie van het datatype nu is gelukt.<br>
Dit is <b>randvoorwaardelijk</b> voor het uitvoeren van wiskundige operaties.<br>

### Rijen

Zorg er nu voor dat bij alle extensions 1 wordt opgeteld.

In [92]:
sales_staff['EXTENSION'] = sales_staff['EXTENSION'] +1
sales_staff

,SALES_STAFF_CODE,FIRST_NAME,LAST_NAME,POSITION_EN,WORK_PHONE,EXTENSION,FAX,EMAIL,DATE_HIRED,SALES_BRANCH_CODE
0,4,Denis,Pagé,Branch Manager,+33 1 68 94 52 20,328.0,+33 1 68 94 56 60,DPage@grtd123.com,1996-11-03,6
1,5,Élizabeth,Michel,Level 3 Sales Representative,+33 1 68 94 52 20,339.0,+33 1 68 94 56 60,EMichel@grtd123.com,1995-06-08,6
2,6,Émile,Clermont,Level 1 Sales Representative,+33 1 68 94 52 20,381.0,+33 1 68 94 56 60,EClermont@grtd123.com,1998-04-07,6
3,7,Étienne,Jauvin,Level 2 Sales Representative,+33 1 68 94 52 20,401.0,+33 1 68 94 56 60,EJauvin@grtd123.com,1997-08-16,6
4,12,Elsbeth,Wiesinger,Level 2 Sales Representative,+(49) 40 663 1990,1821.0,+(49) 40 663 4571,EWiesinger@grtd123.com,1997-02-27,13
...,...,...,...,...,...,...,...,...,...,...
97,120,Giele,Laermans,Level 1 Sales Representative,+32 16 20.73.21,1343.0,+32 16 20.73.32,GLaermans@grtd123.com,1999-11-15,38
98,121,François,De Crée,Level 1 Sales Representative,+32 16 20.73.21,1645.0,+32 16 20.73.32,FDecree@grtd123.com,1999-12-01,38
99,122,Yvette,Lattrez,Level 3 Sales Representative,+32 16 20.73.21,1636.0,+32 16 20.73.32,YLattrez@grtd123.com,1999-12-09,38
100,123,Willi,Seefelder,Level 2 Sales Representative,+(43) 13 79 56 32,328.0,+(43) 13 79 56 33,WSeefelder@grtd123.com,1998-10-28,39
101,124,Sabine,Grüner,Level 3 Sales Representative,+(43) 13 79 56 32,351.0,+(43) 13 79 56 33,SGruner@grtd123.com,1998-02-18,39

Elke 'Branch Manager' wordt nu 'General Manager'. Schrijf code zodat deze wijziging doorgevoerd wordt in het DataFrame.

In [ ]:
sales_staff['POSITION_EN'].where(sales_staff['POSITION_EN'] == 'Branch Manager').replace('Branch Manager', 'General Manager')

0      General Manager
1                  NaN
2                  NaN
3                  NaN
4                  NaN
            ...
97                 NaN
98                 NaN
99                 NaN
100                NaN
101                NaN
Name: POSITION_EN, Length: 102, dtype: object

### Kolommen

Verander de kolomnaam 'POSITION_EN' naar 'POSITION'.

In [105]:
sales_staff.rename({'POSITION_EN' : 'POSITION'}, axis='columns')

,SALES_STAFF_CODE,FIRST_NAME,LAST_NAME,POSITION,WORK_PHONE,EXTENSION,FAX,EMAIL,DATE_HIRED,SALES_BRANCH_CODE
0,4,Denis,Pagé,Branch Manager,+33 1 68 94 52 20,328.0,+33 1 68 94 56 60,DPage@grtd123.com,1996-11-03,6
1,5,Élizabeth,Michel,Level 3 Sales Representative,+33 1 68 94 52 20,339.0,+33 1 68 94 56 60,EMichel@grtd123.com,1995-06-08,6
2,6,Émile,Clermont,Level 1 Sales Representative,+33 1 68 94 52 20,381.0,+33 1 68 94 56 60,EClermont@grtd123.com,1998-04-07,6
3,7,Étienne,Jauvin,Level 2 Sales Representative,+33 1 68 94 52 20,401.0,+33 1 68 94 56 60,EJauvin@grtd123.com,1997-08-16,6
4,12,Elsbeth,Wiesinger,Level 2 Sales Representative,+(49) 40 663 1990,1821.0,+(49) 40 663 4571,EWiesinger@grtd123.com,1997-02-27,13
...,...,...,...,...,...,...,...,...,...,...
97,120,Giele,Laermans,Level 1 Sales Representative,+32 16 20.73.21,1343.0,+32 16 20.73.32,GLaermans@grtd123.com,1999-11-15,38
98,121,François,De Crée,Level 1 Sales Representative,+32 16 20.73.21,1645.0,+32 16 20.73.32,FDecree@grtd123.com,1999-12-01,38
99,122,Yvette,Lattrez,Level 3 Sales Representative,+32 16 20.73.21,1636.0,+32 16 20.73.32,YLattrez@grtd123.com,1999-12-09,38
100,123,Willi,Seefelder,Level 2 Sales Representative,+(43) 13 79 56 32,328.0,+(43) 13 79 56 33,WSeefelder@grtd123.com,1998-10-28,39
101,124,Sabine,Grüner,Level 3 Sales Representative,+(43) 13 79 56 32,351.0,+(43) 13 79 56 33,SGruner@grtd123.com,1998-02-18,39

## Data verwijderen

### Rijen

De medewerkers op indexen 99, 100 en 101 hebben helaas ontslag genomen.<br>
Verwijder de bijbehorende rijen uit het DataFrame. Gebruik slechts één keer de .drop()-methode.

In [111]:
sales_staff.drop([99, 100, 101])

,SALES_STAFF_CODE,FIRST_NAME,LAST_NAME,POSITION_EN,WORK_PHONE,EXTENSION,FAX,EMAIL,DATE_HIRED,SALES_BRANCH_CODE
0,4,Denis,Pagé,Branch Manager,+33 1 68 94 52 20,328.0,+33 1 68 94 56 60,DPage@grtd123.com,1996-11-03,6
1,5,Élizabeth,Michel,Level 3 Sales Representative,+33 1 68 94 52 20,339.0,+33 1 68 94 56 60,EMichel@grtd123.com,1995-06-08,6
2,6,Émile,Clermont,Level 1 Sales Representative,+33 1 68 94 52 20,381.0,+33 1 68 94 56 60,EClermont@grtd123.com,1998-04-07,6
3,7,Étienne,Jauvin,Level 2 Sales Representative,+33 1 68 94 52 20,401.0,+33 1 68 94 56 60,EJauvin@grtd123.com,1997-08-16,6
4,12,Elsbeth,Wiesinger,Level 2 Sales Representative,+(49) 40 663 1990,1821.0,+(49) 40 663 4571,EWiesinger@grtd123.com,1997-02-27,13
...,...,...,...,...,...,...,...,...,...,...
94,117,Frank,Jever,Level 3 Sales Representative,+(41) 17 12 13 14,1157.0,+(41) 17 12 13 20,FJever@grtd123.com,1999-10-18,37
95,118,Gianni,Vertemati,Level 1 Sales Representative,+(41) 17 12 13 14,1257.0,+(41) 17 12 13 20,GVertemati@grtd123.com,2000-02-10,37
96,119,Gracy,Gellens,Branch Manager,+32 16 20.73.21,1352.0,+32 16 20.73.32,GGellens@grtd123.com,1999-09-10,38
97,120,Giele,Laermans,Level 1 Sales Representative,+32 16 20.73.21,1343.0,+32 16 20.73.32,GLaermans@grtd123.com,1999-11-15,38
98,121,François,De Crée,Level 1 Sales Representative,+32 16 20.73.21,1645.0,+32 16 20.73.32,FDecree@grtd123.com,1999-12-01,38

### Kolommen

Faxen zijn inmiddels ouderwets: niemand gebruikt zijn/haar faxnummer nog.<br>
Verwijder de bijbehorende kolom uit het DataFrame.

In [112]:
sales_staff.drop(columns="FAX")

,SALES_STAFF_CODE,FIRST_NAME,LAST_NAME,POSITION_EN,WORK_PHONE,EXTENSION,EMAIL,DATE_HIRED,SALES_BRANCH_CODE
0,4,Denis,Pagé,Branch Manager,+33 1 68 94 52 20,328.0,DPage@grtd123.com,1996-11-03,6
1,5,Élizabeth,Michel,Level 3 Sales Representative,+33 1 68 94 52 20,339.0,EMichel@grtd123.com,1995-06-08,6
2,6,Émile,Clermont,Level 1 Sales Representative,+33 1 68 94 52 20,381.0,EClermont@grtd123.com,1998-04-07,6
3,7,Étienne,Jauvin,Level 2 Sales Representative,+33 1 68 94 52 20,401.0,EJauvin@grtd123.com,1997-08-16,6
4,12,Elsbeth,Wiesinger,Level 2 Sales Representative,+(49) 40 663 1990,1821.0,EWiesinger@grtd123.com,1997-02-27,13
...,...,...,...,...,...,...,...,...,...
97,120,Giele,Laermans,Level 1 Sales Representative,+32 16 20.73.21,1343.0,GLaermans@grtd123.com,1999-11-15,38
98,121,François,De Crée,Level 1 Sales Representative,+32 16 20.73.21,1645.0,FDecree@grtd123.com,1999-12-01,38
99,122,Yvette,Lattrez,Level 3 Sales Representative,+32 16 20.73.21,1636.0,YLattrez@grtd123.com,1999-12-09,38
100,123,Willi,Seefelder,Level 2 Sales Representative,+(43) 13 79 56 32,328.0,WSeefelder@grtd123.com,1998-10-28,39
101,124,Sabine,Grüner,Level 3 Sales Representative,+(43) 13 79 56 32,351.0,SGruner@grtd123.com,1998-02-18,39